### ISSUE TITLE
Use of Proc

### ISSUE THREAD

**Issue by hillarioh** [acushlakoncept/tic-tac-toe#7]
There is a lot of usage of proc

**Comment by acushlakoncept** [comment]
Thank you for your observation @hillarioh 👍 

Since we needed to compartmentalize most of our methods and keep the main.rb simple and let the Classes be responsible for their methods.

Proc was the most effective way of calling all the `puts` and `gets` on the main.

As long as it doesn't cause the program to slow or affect it in any way. If there is a set back to this please kindly share.

Thank you.
